exam/urls.py
from django.urls import path

from . import views

app_name = 'exam'
urlpatterns = [
    path('', views.index, name='index'),
    path('test',views.test,name='test'),
    path('result',views.result,name='result'),
    
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    
    path('login',views.login_view,name='login_view'),
    path('logout',views.logout_view,name='logout_view'),
    path('signup',views.signup_view,name='signup_view'),
    # path('otp',views.otp_view,name='otp_view'),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static
import home.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quiz_master/',include('quiz_master.urls')),
    path('home/',include('home.urls')),
    path('user_profile/',include('user_profile.urls')),
    path('exam/',include('exam.urls')),
    path('',home.views.login_view,name='login_view'),
    
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms.widgets import PasswordInput


class LoginForm(forms.Form):
    username = forms.CharField(label='Username')
    password = forms.CharField(widget=PasswordInput())


class SignupForm(UserCreationForm):


   # email = forms.EmailField(max_length=200,help_text='Required')

    class Meta:
        model = User
        fields = ('username','password1','password2')

class OtpForm(forms.Form):
    otp = forms.CharField(max_length=5,widget = PasswordInput())

home/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, Http404
from django.contrib import messages
from .forms import LoginForm, SignupForm
from random import randrange
from django.contrib.auth.models import User

# Create your views here.

def login_view(request):


	form = LoginForm(request.POST)
	if request.method == 'POST':
		user = authenticate(username=request.POST['username'], password=request.POST['password'])

		if user is not None:
			login(request,user)
			if user.is_superuser:
				return redirect('admin:index')

			if user.has_perm('quiz_master.add_question'):
				return redirect('quiz_master:questions_view')
			else:
				return redirect('user_profile:index')
		else:
			messages.warning(request,'Authentication failiure!')
			
	context = {'form':form}

	return render(request,'home/home.html',context)






def logout_view(request):
	
	logout(request)
	messages.warning(request,'Successfully logged out')
	return redirect('home:login_view')






def signup_view(request):
	
	form = SignupForm(request.POST)
	if request.method == 'POST':
		
		if form.is_valid():

			

			user = form.save()
			user.is_active = True
			user.save()
			user = authenticate(username=request.POST['username'], password=request.POST['password1'])
			request.session['username']=username=request.POST['username']
			
			return redirect('home:login_view')
			
			

	return render(request,'home/signup.html',{'form':form})

home/templates/home/home.html
{% extends "base_without_navbar.html" %}
{% load crispy_forms_tags %}
{% block title %}Login{% endblock title %}
{% block content %}




<h1>* Improve your Knowledge<br>
	* Practice for competitive exams<br>
	* Track your progress</h1>
<div style="float: right;">Don't have an account? <a href="{% url 'home:signup_view' %}" > Sign up</a></button>


</div>
	<div class="container">
		<div  class="carousel slide w-50" data-bs-ride="carousel">
			<div class="carousel-inner">
			<div class="carousel-item active" data-bs-interval="3000">
				<h1>Science</h1>
			</div>
			<div class="carousel-item" data-bs-interval="3000">
				<h1>History</h1>
			</div>
			<div class="carousel-item " data-bs-interval="3000">
				<h1>English</h1>
			</div>
			<div class="carousel-item " data-bs-interval="3000">
				<h1>General Knowledge</h1>
			</div>
			</div>
		</div>
	</div>
<form action="" method="POST" style="width:100%;max-width:330px;padding:15px;
margin: auto;">

<div class="mt-auto" style="float: right;">
	{% if messages %}
	
		{% for message in messages %}
		
			<h4 style="color:#e8491d;">{{message}}</h4>

		{% endfor %}
	{% endif %}
</div>
	
	
	{% csrf_token %}
	{{form|crispy}}
	<button type="submit" class="btn btn-dark mt-1 " style="float: right;"> Login</button>
	</div>
</form>



{% endblock content %}



	

home/templates/home/otp.html
{% extends "base_without_navbar.html" %}
{% load crispy_forms_tags %}
{% block content %}



<form class="mt-5" action="" method="POST" style="width:100%;max-width:200px;padding:15px;height: 50px;
margin: auto; margin-top:200px;">
	
	<div class="mt-auto" style="float: right;">
		{% if messages %}
		
			{% for message in messages %}
			
				<h4 style="color:#e8491d;">{{message}}</h4>

			{% endfor %}
		{% endif %}
	</div>

	{% csrf_token %}
	{{form|crispy}}
	<button type="submit" class="btn btn-dark mt-1 " style="float: right;"> Validate</button>
	
</form>


{% endblock content %}

home/templates/home/signup.html
{% extends "base_without_navbar.html" %}
{% load crispy_forms_tags %}
{% block title %}Signup{% endblock title %}
{% block content %}



<form class="mt-5" action="" method="POST" style="width:100%;max-width:500px;padding:15px;
margin: auto;">
	
	<div class="mt-auto" style="float: right;">
		{% if messages %}
		
			{% for message in messages %}
			
				<h4 style="color:#e8491d;">{{message}}</h4>

			{% endfor %}
		{% endif %}
</div>

	{% csrf_token %}
	{{form|crispy}}
	<button type="submit" class="btn btn-dark mt-1 " style="float: right;"> Sign Up</button>
	</div>
	
</form>


{% endblock content %}