exam/urls.py
from django.urls import path

from . import views

app_name = 'exam'
urlpatterns = [
    path('', views.index, name='index'),
    path('test',views.test,name='test'),
    path('result',views.result,name='result'),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static
import home.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quiz_master/',include('quiz_master.urls')),
    path('home/',include('home.urls')),
    path('user_profile/',include('user_profile.urls')),
    path('exam/',include('exam.urls')),
    path('',home.views.login_view,name='login_view'),
    
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

user_profile/urls.py
from django.urls import path

from . import views
app_name = 'user_profile'
urlpatterns = [
    path('', views.index, name='index'),
]

exam/models.py
from django.db import models
from django.contrib.auth.models import User
from django.http.response import Http404
from quiz_master.models import Question
import uuid
# Create your models here.
MAX_SCORE=20
class Exam(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True,primary_key=True)
    created = models.DateTimeField(auto_now_add=True)
    attended = models.BooleanField(default=False)
    total_score = models.FloatField(default=20)
    obtained_score=models.FloatField(default=0)
    category=models.CharField(max_length=200,default='Mixed')

    def __str__(self):
        return f"{self.id} {self.user} [ {self.category} ] {self.created} "

    def createExam(user_id,category):
        generated_id=uuid.uuid4()
        user = User.objects.get(id=user_id)
        data=Exam(user=user,id=generated_id,category=category)
        data.save()
        exam = Exam.objects.get(id=generated_id)
        AnswerSheet.fillAnswersheet(Question.prepareQuestions(category),exam)
        return str(generated_id)
        
    def insertScore(score,exam_id):
        Exam.objects.filter(id=exam_id).update(obtained_score=score,attended=True)

    
class AnswerSheet(models.Model):

    exam = models.ForeignKey(Exam,on_delete=models.CASCADE)
    question_no = models.CharField(max_length=10,default='')
    question_text = models.CharField(max_length=200,default='')
    choice_1 = models.CharField(max_length=200,default='choice_1')
    choice_2 = models.CharField(max_length=200,default='choice_2')
    choice_3 = models.CharField(max_length=200,default='choice_3')
    choice_4 = models.CharField(max_length=200,default='choice_4')
    answer = models.CharField(max_length=200,default='')
    selected_choice = models.CharField(max_length=200,default='')
    


    def fillAnswersheet(question_obj_list,exam):
        for question_obj in question_obj_list:
            data = AnswerSheet(
            exam=exam,
            question_no = question_obj.id,
            question_text = question_obj.question_text,
            choice_1 = question_obj.choice_1,
            choice_2 = question_obj.choice_2,
            choice_3 = question_obj.choice_3,
            choice_4 = question_obj.choice_4,
            answer = question_obj.answer)
            data.save()
            
        #AnswerSheet.calculateScore(question_obj_list,answer_sheet)



    def saveAnswers(answers,exam_id):
        if Exam.objects.get(id=exam_id).attended:
            raise Http404
        else:
            for i in range(len(answers)):
                if answers[i]==None:
                    answers[i]="Not Answered"
                AnswerSheet.objects.filter(exam=exam_id,question_no=i+1).update(selected_choice=answers[i])
            Exam.insertScore(AnswerSheet.calculateScore(exam_id),exam_id)

    def calculateScore(exam_id):
        score=0
        qs=AnswerSheet.objects.filter(exam=exam_id)
        for object in qs:
            if object.answer==object.selected_choice:
                score+=1
        return score
   

exam/forms.py
from django import forms
from django.forms import widgets
from django.forms.widgets import RadioSelect
from django.http import request
from quiz_master.models import Question
SUBJECT_CHOICES = (
    ('Science','Science'),
    ('History','History'),
    ('General Knowledge','General Knowledge'),
    ('English','English'),
    ('Mixed','Mixed')
)




class ExamSettingsForm(forms.Form):
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES)

'''
class ExamForm(forms.Form):
    question_obj_list=Question.prepareQuestions('Science')
    #question= forms.ChoiceField(widget=RadioSelect(),required=False)
   
    for question_obj in question_obj_list: 
        q1=forms.Field(label=question_obj.question_text,widget=RadioSelect(),required=False)
'''       
        

exam/views.py
from django.forms import fields
from django.http import request
from django.http.response import Http404, HttpResponse
from django.shortcuts import redirect, render
from .forms import ExamSettingsForm
from django.contrib.auth.decorators import login_required
from .models import AnswerSheet, Exam

import random
# Create your views here.


NUM_QUESTIONS=8 #should be something divisible by 4 because there is 4 categories


# index view

@login_required
def index(request):
    
    if 'exam_id' in request.session:
        AnswerSheet.objects.filter(exam=request.session['exam_id']).delete()
    form = ExamSettingsForm(request.POST)
    if request.method == 'POST':
        category = request.POST.get('subject')
        request.session['exam_id']=Exam.createExam(request.user.id,category)
        
        return redirect('exam:test')
    context = {'form':form}
    
    return render(request,'exam/exam_home.html',context)


# test view

@login_required
def test(request):
    question_obj_list=AnswerSheet.objects.filter(exam=request.session['exam_id'])
    context = {'question_obj_list':question_obj_list}
    answers=[]
    if request.method == 'POST':
        for i in range(NUM_QUESTIONS):
            answers.insert(i,request.POST.get(str(i+1)))
    
        AnswerSheet.saveAnswers(answers,request.session['exam_id']) 
        return redirect('exam:result')
    return render(request,'exam/exam_main.html',context)




# the score view

def result(request):

    answers=AnswerSheet.objects.filter(exam=request.session['exam_id'])
    
    score=int((Exam.objects.get(id=request.session['exam_id'])).obtained_score)
    category=(Exam.objects.get(id=request.session['exam_id'])).category
    context={'answers':answers,'score':score,'category':category}
   # AnswerSheet.objects.filter(exam=request.session['exam_id']).delete()
    return render(request,'exam/results.html',context)

exam/templates/exam/exam_home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Exam category{% endblock title %}
{% block content %}



<form action="" method="POST" >
<div class="form-group" style="margin-top:200px;">
	{% csrf_token %}
	{{form|crispy}}
	<button type="submit" class="btn btn-dark mt-2" style="float:right;"> Start Test</button>
</div>
</form>

{% endblock content %}

exam/templates/exam/exam_main.html
{% extends "base.html" %}

{% block title %}Exam{% endblock title %}
{% block content %}


<script>
window.onunload = function() {
   alert("please stay on the page")
};
</script>
	

<form action="" method="POST" required>
	{% csrf_token %}

	{% for question_obj in question_obj_list %}

	
	
	<div class="card mt-5">
		<div class="card-header text-light bg-dark">
			<h5>Question : {{question_obj.question_no}}</h5>
		  </div>
		<div class="card-body">
		<h4>{{question_obj.question_text}}</h4>
			<div class="form-check" validate>
				<div class="form-check form-check-inline">
					<input class="form-check-input" type="radio" name="{{question_obj.question_no}}" id="inlineRadio1" value="{{question_obj.choice_1}}" >
					<label class="form-check-label" for="inlineRadio1">{{question_obj.choice_1}}</label>
				</div>
				<div class="form-check form-check-inline">
					<input class="form-check-input" type="radio" name="{{question_obj.question_no}}" id="inlineRadio2" value="{{question_obj.choice_2}}">
					<label class="form-check-label" for="inlineRadio2">{{question_obj.choice_2}}</label>
				</div>
				<div class="form-check form-check-inline">
					<input class="form-check-input" type="radio" name="{{question_obj.question_no}}" id="inlineRadio3" value="{{question_obj.choice_3}}">
					<label class="form-check-label" for="inlineRadio3">{{question_obj.choice_3}}</label>
				</div>
				<div class="form-check form-check-inline">
					<input class="form-check-input" type="radio" name="{{question_obj.question_no}}" id="inlineRadio4" value="{{question_obj.choice_4}}">
					<label class="form-check-label" for="inlineRadio4">{{question_obj.choice_4}}</label>
				</div>
			</div>
		</div>
		
	</div>
	{% endfor %}
	
	<button type="submit" class="btn btn-dark mt-5"> Submit</button>
</form>

{% endblock content %}

exam/templates/exam/results.html
{% extends "base.html" %}

{% load static %}
{% block title %}Results{% endblock title %}
{% block content %}



<div class="card text-center">
  <div class="card-header">
    
    Category : {{category}}
   
  </div>
    <div class="card-body">
      <h5 class="card-title"><h5>Your Score is : {{score}}</h5>
      <p class="card-text">Please review your answers given below</p>
      <a href="{%url 'exam:index'%}" class="btn btn-primary">Try another exam</a>
      <a href="{%url 'user_profile:index'%}" class="btn btn-primary">Goto Profile</a>
    </div>
</div>

<table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Question</th>
        <th scope="col">Your Answer</th>
        <th scope="col">Correct Answer</th>
      </tr>
    </thead>
    <tbody>
        {% for ans in answers %}
        
      <tr id="rows">
        <th scope="row">{{ans.question_no}}</th>
        <td>{{ans.question_text}}</td>
        <td>{{ans.selected_choice}}</td>
        <td>{{ans.answer}}</td>
        <td><a href="https://www.google.com/search?q={{ans.question_text}}" target="_blank">Additional Info</a></td>
      </tr>

        {% endfor %}
    </tbody>
  </table>

  
{% endblock content %}

{% block scripts %}
<script src="{% static 'js/results.js'%}">

</script>
{% endblock scripts %}