exam/urls.py
from django.urls import path

from . import views

app_name = 'exam'
urlpatterns = [
    path('', views.index, name='index'),
    path('test',views.test,name='test'),
    path('result',views.result,name='result'),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static
import home.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quiz_master/',include('quiz_master.urls')),
    path('home/',include('home.urls')),
    path('user_profile/',include('user_profile.urls')),
    path('exam/',include('exam.urls')),
    path('',home.views.login_view,name='login_view'),
    
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

quiz_master/urls.py
from django.urls import path

from . import views


app_name = 'quiz_master'
urlpatterns = [
    path('questions_view',views.questions_view,name='questions_view'),
    path('add_question',views.add_question,name='add_question'),
    path('delete_question/<int:question_id>/',views.delete_question,name='delete_question'),
    path('change_question/<int:question_id>/',views.change_question,name='change_question'),
    
]

quiz_master/models.py
import datetime
from django.db import models
from django.utils.timezone import now
import random

NUM_QUESTIONS=8

SUBJECT_LIST=['Science','History','General Knowledge','English']

SUBJECT_CHOICES = (
    ('Science','Science'),
    ('History','History'),
    ('General Knowledge','General Knowledge'),
    ('English','English'),
)
QUESTION_LEVEL = (
    ('Easy','Easy'),
    ('Medium','Medium'),
    ('Hard','Hard'),
)

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    choice_1 = models.CharField(max_length=200)
    choice_2 = models.CharField(max_length=200)
    choice_3 = models.CharField(max_length=200)
    choice_4 = models.CharField(max_length=200)
    answer   = models.CharField(max_length=200)
    category = models.CharField(max_length=200,default='General Knowledge',choices=SUBJECT_CHOICES)
    level = models.CharField(max_length=200,default='Easy',choices=QUESTION_LEVEL)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.question_text} [ {self.category} ] [ {self.level} ]"


    def prepareQuestions(subject):
        if subject=="Mixed":
            question_obj_list=[]

            for i in SUBJECT_LIST:
                
                qs=Question.objects.filter(category=i)
                question_obj_list.extend(random.sample(list(qs),int(NUM_QUESTIONS/len(SUBJECT_LIST))))
            count=1
            for j in question_obj_list:
                j.id=count
                count+=1
            return question_obj_list
        else:
            qs = Question.objects.filter(category=subject)
            question_obj_list=random.sample(list(qs),NUM_QUESTIONS)

            count=1
            for j in question_obj_list:
                j.id=count
                count+=1
                
            return question_obj_list

quiz_master/forms.py
from django import forms
from .models import Question
from django.contrib.auth.models import User
from django.forms.widgets import PasswordInput


class LoginForm(forms.Form):
    username = forms.CharField(label='Username')
    password = forms.CharField(widget=PasswordInput())


class QuestionAddForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ('question_text','choice_1','choice_2','choice_3','choice_4','answer','category','level')

class QuestionUpdateForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('question_text','choice_1','choice_2','choice_3','choice_4','answer','category','level')

quiz_master/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, SUBJECT_LIST
from django.urls import reverse
from .forms import LoginForm,QuestionAddForm,QuestionUpdateForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import permission_required


@permission_required('quiz_master.add_question')

def questions_view(request):
	question_list=Question.objects.all()
	length=len(question_list)
	context={'question_list':question_list,'length':length,'category_list':SUBJECT_LIST}	
	return render(request, 'quiz_master/questions_view.html', context)

@permission_required('quiz_master.add_question')

def add_question(request):
	form = QuestionAddForm(request.POST)
	if request.method == 'POST':
		data=Question(question_text=request.POST['question_text'],
		choice_1=request.POST['choice_1'],
		choice_2=request.POST['choice_2'],
		choice_3=request.POST['choice_3'],
		choice_4=request.POST['choice_4'],
		answer=request.POST.get('answer'),
		category=request.POST.get('category'),
		level=request.POST.get('level'))
		data.save()
		return redirect('quiz_master:questions_view')
	return render(request,'quiz_master/add_question.html',{'form':form})
	



@permission_required('quiz_master.add_question')
def change_question(request,question_id):
	selected_question=get_object_or_404(Question,id=question_id)
	form = QuestionUpdateForm(instance=selected_question)

	if request.method == 'POST':
		selected_question.question_text=request.POST['question_text']
		selected_question.choice_1=request.POST['choice_1']
		selected_question.choice_2=request.POST['choice_2']
		selected_question.choice_3=request.POST['choice_3']
		selected_question.choice_4=request.POST['choice_4']
		selected_question.answer=request.POST.get('answer')
		selected_question.category=request.POST.get('category')
		selected_question.level=request.POST.get('level')
		selected_question.save()
		messages.warning(request,'Question updated')
		return redirect('quiz_master:questions_view')
	return render(request,'quiz_master/change_question.html',{'form':form})

@permission_required('quiz_master.add_question')
def delete_question(request,question_id):
	
	selected_question=Question.objects.get(id=question_id)
	selected_question.delete()
	messages.warning(request,'Question deleted')
	return redirect('quiz_master:questions_view')

	

quiz_master/templates/quiz_master/add_question.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Signup{% endblock title %}
{% block content %}



<form class="mt-5" action="" method="POST" style="width:100%;max-width:500px;padding:15px;
margin: auto;">
	
	<div class="mt-auto" style="float: right;">
		{% if messages %}
		
			{% for message in messages %}
			
				<h4 style="color:#e8491d;">{{message}}</h4>

			{% endfor %}
		{% endif %}
</div>

	{% csrf_token %}
	{{form|crispy}}
	<button type="submit" class="btn btn-dark mt-1 " style="float: right;"> Create</button>
	<a class="btn btn-primary mt-1" style="float: left;" href="{% url 'quiz_master:questions_view' %}">Cancel</a>

	</div>
	
</form>


{% endblock content %}

quiz_master/templates/quiz_master/change_question.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Update_question{% endblock title %}
{% block content %}



<form class="mt-5" action="" method="POST" style="width:100%;max-width:500px;padding:15px;
margin: auto;">
	
	<div class="mt-auto" style="float: right;">
		{% if messages %}
		
			{% for message in messages %}
			
				<h4 style="color:#e8491d;">{{message}}</h4>

			{% endfor %}
		{% endif %}
	</div>

	{% csrf_token %}
	{{form|crispy}}
	
	<button type="submit" class="btn btn-dark mt-1 " style="float: right;">Update</button>
	<a class="btn btn-primary mt-1" style="float: left;" href="{% url 'quiz_master:questions_view' %}">Cancel</a>

	</div>
</form>


{% endblock content %}

quiz_master/templates/quiz_master/questions_view.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Questions{% endblock title %}
{% block content %}

<div class="mt-auto">
	{% if messages %}
	
		{% for message in messages %}
		
			<h5 style="color:#e8491d;">{{message}}</h5>

		{% endfor %}
	{% endif %}
</div>

<section id="question_form">
	<div class="container" >
	<a href="{% url 'quiz_master:add_question' %}" style="float:right;" ><button class="btn btn-dark mt-1">Add question</button></a>
	category: <select id="category"><option>All</option>{%for category in category_list %}<option>{{category}}</option>{% endfor %}</select>
	<table border="0" style="min-width:100%;">
		<th>ID</th>
		<th>Question</th>
		<th>Category</th>

		{% for question in question_list%}
		<tr class="{{question.category}}"><td>{{question.id}}</td>
				<td>{{question.question_text}}</td>
				<td>{{question.answer}}</td>
				<td style="padding-left:20px;"><a href="{% url 'quiz_master:change_question' question.id %}">edit</a></td>
				<td><a href="{% url 'quiz_master:delete_question' question.id %}" onclick="return confirm('Are you sure you want to delete this question')">delete</a></td>
				
		</tr>

		{%endfor%}

		
		
	</table>

	</div>
</section>

{% endblock content %}

{% block scripts %}
<script src="{% static 'js/questions_by_category.js'%}">

</script>
{% endblock scripts %}