exam/urls.py
from django.urls import path

from . import views

app_name = 'exam'
urlpatterns = [
    path('', views.index, name='index'),
    path('test',views.test,name='test'),
    path('result',views.result,name='result'),
    
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    
    path('login',views.login_view,name='login_view'),
    path('logout',views.logout_view,name='logout_view'),
    path('signup',views.signup_view,name='signup_view'),
    # path('otp',views.otp_view,name='otp_view'),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static
import home.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quiz_master/',include('quiz_master.urls')),
    path('home/',include('home.urls')),
    path('user_profile/',include('user_profile.urls')),
    path('exam/',include('exam.urls')),
    path('',home.views.login_view,name='login_view'),
    
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- favicon --> 
    {% comment %}<link rel="shortcut icon" href="{% static 'favicon.ico' %}" /> {% endcomment %}

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <!-- jquery -->
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>

    <!-- Bootstrap js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
   
    <!-- Dropzone js -->
    {% comment %}<link rel="stylesheet" href="{% static 'dropzone.css' %}">
    <script src="{% static 'dropzone.js' %}" defer></script>{% endcomment %}

    <!-- Custom js & css -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    

    <title>Mock Test Platform|{% block title %}{% endblock title %}</title>
    {% block scripts %}
    {% endblock scripts %}
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container mt-3 mb-3">
        {% block content %}
        {% endblock content %}
    </div>

    
  </body>
 
</html>

templates/base_without_navbar.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- favicon --> 
    {% comment %}<link rel="shortcut icon" href="{% static 'favicon.ico' %}" /> {% endcomment %}

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <!-- jquery -->
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>

    <!-- Bootstrap js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
   
    <!-- Custom js & css -->
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <title>Mock Test Platform|{% block title %}{% endblock title %}</title>
    {% block scripts %}
    {% endblock scripts %}
  </head>
  <body>
    <div class="container mt-3 mb-3">
        {% block content %}
        {% endblock content %}
    </div>

    
  </body>
 
</html>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    {% comment %}
    <a class="navbar-brand" href=""><img src="{% static 'logo.png' %}" class="logo-sm"></a>

    
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="">Home</a>
        </li>
      </ul>
    </div>
    {% endcomment %}

    {% if request.user.is_authenticated %}
      <div class="nav-item dropdown">
        <div class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <img src="" class="">&nbsp;{{request.user}}
        </div>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          
          <li><a class="dropdown-item" href="{% url 'home:logout_view' %}">Logout</a></li>
        </ul>
      </div>
    {% endif %}
  </div>
</nav>